---
kind: pipeline
type: docker
name: ses-email-service-lambda

platform:
  os: linux
  arch: amd64

steps:
- name: Zip
  image: kramos/alpine-zip
  commands:
  - zip ./email-blacklist.zip email_blacklist.py

- name: Deploy
  image: liquidfish/aws-cli
  commands:
  - aws lambda update-function-code --function-name EmailBlacklist --zip-file fileb://./email-blacklist.zip
  - echo "Publishing Lambda version $(aws lambda publish-version --function-name EmailBlacklist | jq -r .Version)"
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY

trigger:
  branch:
  - master

---
kind: pipeline
type: docker
name: ses-email-service

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: plugins/docker
  settings:
    password:
      from_secret: LF_DOCKER_HUB_PASSWORD
    repo: liquidfish/ses-email-service
    tags:
    - latest
    - ${DRONE_COMMIT}
    username:
      from_secret: LF_DOCKER_HUB_USERNAME

- name: deploy
  image: lachlanevenson/k8s-helm
  commands:
  - apk add curl
  - curl -Lo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod a+x /usr/local/bin/kubectl
  - curl -fSsL https://github.com/digitalocean/doctl/releases/download/v1.43.0/doctl-1.43.0-linux-amd64.tar.gz -o - | tar -xvzf-
  - mv doctl /usr/local/bin/doctl
  - doctl auth init -t $LF_DO_API_KEY
  - doctl kubernetes cluster kubeconfig save $LF_DO_K8S_NAME
  - kubectl apply -f k8s_definitions/
  - kubectl -n ses-email-service set image deployment/ses-email-service-deployment ses-email-service=liquidfish/ses-email-service:${DRONE_COMMIT} --record
  environment:
    LF_DO_API_KEY:
      from_secret: LF_DO_API_KEY
    LF_DO_K8S_NAME:
      from_secret: LF_DO_K8S_NAME

- name: notify
  image: appleboy/drone-discord
  settings:
    message: "**{{#success build.status}}:white_check_mark:{{ else }}:x:{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}**\n\n{{#if build.pull }}\n  Pull Request: #{{ build.pull }} https://bitbucket.org/{{ repo.owner }}/{{ repo.name }}/pull-requests/{{ build.pull }}\n{{/if}}\nCommit: {{ build.commit }} - https://bitbucket.org/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.commit }}\nBranch: {{ build.branch }} - https://bitbucket.org/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}\nAuthor: {{ build.author }}\n\n{{ build.link }}\n"
    username: LiquidCI
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_SECRET

trigger:
  ref:
  - refs/heads/master

...
