version: 2.1
jobs:
  build:
    docker:
      - image: clevyr/circleci-ecr-builder

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Zip Lambda Code
          command: zip ./email-blacklist.zip email_blacklist.py
      - run:
          name: Update Lambda Code
          command: aws lambda update-function-code --function-name email-blacklist --zip-file fileb://./email-blacklist.zip

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
