apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: email-liquidfish-xyz
  namespace: ses-email-service
spec:
  secretName: email-liquidfish-xyz-tls
  dnsNames:
  - email.liquidfish.xyz
  issuerRef:
    name: letsencrypt-liquidfish-xyz
    kind: ClusterIssuer
    group: cert-manager.io
