apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: email-mcswain-dev
  namespace: ses-email-service
spec:
  secretName: email-mcswain-dev-tls
  dnsNames:
  - email.mcswain.dev
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
