apiVersion: v1
kind: Service
metadata:
  name: ses-email-service
  namespace: ses-email-service
spec:
  selector:
    app: ses-email-service
  ports:
    - name: tcp-smtp
      protocol: TCP
      port: 465
      targetPort: 465
