apiVersion: v1
kind: Service
metadata:
  name: ses-email-service
  namespace: ses-email-service
spec:
  selector:
    app: ses-email-service
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
