apiVersion: apps/v1
kind: Deployment
metadata:
  name: ses-email-service
  namespace: ses-email-service
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: ses-email-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ses-email-service
    spec:
      containers:
      - name: ses-email-service
        image: ghcr.io/usa-reddragon/ses-email-service:main@sha256:a9b337ff1d6dbe814103e54233e42bdd149eeb2516d40464db4fccca111bc7e7
        imagePullPolicy: Always
        volumeMounts:
        - name: ssl
          mountPath: "/ssl"
          readOnly: true
        env:
        - name: USE_BLOCKLIST
          value: "true"
        - name: DEBUG
          value: "true"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: SES_RATE_LIMIT
          value: "14"
        - name: AWS_SMTP_HOST
          value: "email-smtp.us-east-1.amazonaws.com"
        - name: AWS_SMTP_PORT
          value: "587"
        - name: DYNAMODB_TABLE
          value: email-blocklist-blocklist
        - name: DYNAMODB_API_KEYS_TABLE
          value: email-blocklist-api_keys
        - name: ENABLE_SSL
          value: "true"
        - name: SERVER_FQDN
          value: "email.mcswain.dev"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ses-email-service
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ses-email-service
              key: aws-secret-access-key
        - name: AWS_SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: ses-email-service
              key: aws-smtp-username
        - name: AWS_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ses-email-service
              key: aws-smtp-password
        ports:
        - containerPort: 465
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
      volumes:
      - name: ssl
        secret:
          secretName: email-mcswain-dev-tls
