name: Build Email Service

on:
  pull_request:
  push:
    branches: ['main']
    tags: ['v*']
    paths-ignore:
      - 'infra/k8s/**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@e7afc0ee5060bc77e9a4a7d0af278f8e5716b668 # v2.0.20
    with:
      push: ${{ github.event_name != 'pull_request' }}
