name: Build Email Blacklist Lambda

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./infra/aws

permissions:
  id-token: write      # Required for aws-actions/configure-aws-credentials
  contents: read       # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::803205869942:role/github-actions-ses-email-service
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Place secret variables
        run: |
          echo "${TFVARS}" | base64 -d > variables.tfvars
        env:
          TFVARS: ${{ secrets.TFVARS }}

      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve -var-file=variables.tfvars
